### ISSUE TITLE
Research best bucket for us

### ISSUE THREAD

**Issue by b5er** [b5er/wags_web#13]

**Comment by b5er** [comment]
- Google bucket
- AWS bucket
- Droplet bucket

**Comment by MikhailSorokin** [comment]
Market Share:
(1) - Google Cloud platform in third place with an 8% market share. (Azure - Second)
(2) - AWS had revenues of $6.2 billion and an IaaS market share of 31%
(3) - Droplet - ??

Pricing:

(1) - Google - just need to specify memory that we will want, and we pay for memory used. 
(2) - Amazon - Depending on instance, could pay based on time used or time server is up - could be costly.
(3) - Droplet - One-time installation of VM. Predictable, pay-as-you-go pricing

Reliability:

(1) - Google had an average downtime of 11 hours in 2016
(2) - Amazon was 2 hours
(3) - Droplet - ??

Database:
- All support MongoDB integration, which is what we are using with the backend. MLab can handle this with backups of data as well.

Utilites;
(2) - Google - Has a really good Image vision library if we want to do something on that end.

Migration:

We are using mLab right now - we can transfer to MongoDB Atlas [using this link](https://docs.mongodb.com/guides/cloud/migrate-from-mlab/#migrate-an-mlab-cluster-to-atlas
). The reason for doing this if we want to use the Utilites mentioned in the section above. MLab is just a database storage center. This is very good if we just want to maintain a lot of information. However, if we want to use some utilites - we should consider the migration to MongoDB Atlas that will allow us to use these tools.

Sources:

[AWS vs Google Cloud](https://www.youtube.com/watch?v=RMnMIpEtGsE)
[Droplet](https://www.digitalocean.com/products/droplets/)

**Comment by MikhailSorokin** [comment]
The consensus seems to be: go with mLab and Google Cloud for now. Use Now to deploy the server - separate from the storage - and if we decide to use any external tool functionality such as Computer Vision tools, we will switch over [using this link](https://docs.mongodb.com/guides/cloud/migrate-from-mlab/#migrate-an-mlab-cluster-to-atlas).
