### ISSUE TITLE
recurrent and one-payment stripe

### ISSUE THREAD

**Issue by b5er** [b5er/wags_web#33]

**Comment by MikhailSorokin** [comment]
This is set up, but not with a call to the frontend. Will work on that.

**Comment by b5er** [comment]
Is this already done, I thought we had this

**Comment by MikhailSorokin** [comment]
Yes, but I remember you wanted to communicate with the frontend, which I did not set up yet and I think had a todo left in there.

**Comment by b5er** [comment]
Ah interesting. I'll take a look

**Comment by MikhailSorokin** [comment]
This is in master
