### ISSUE TITLE
Work on integrating the Stripe API completely with the front-end.

### ISSUE THREAD

**Issue by MikhailSorokin** [b5er/wags_web#4]
Work in branch stripe_donation for this issue.

**Comment by b5er** [comment]
@MikhailSorokin are the `console.logs` needed in donation.js?

**Comment by b5er** [comment]
Almost done, when you get a chance can you change the keys to the `..._test_...` and see if it works.

**Comment by b5er** [comment]
Now the frontend functionality is looking good and everything works as expected. 
**Note: the stripe popup should not be in prod, @b5er will work on making it more user-friendly.
