### ISSUE TITLE
Dashboard setup

### ISSUE THREAD

**Issue by b5er** [b5er/wags_web#7]

**Comment by b5er** [comment]
Check for functionality: 
- When a user clicks on side-menu does it change content (ie from `Home` to `Medical`)
- Arrow next to `Pepz` works as intended

**Comment by MikhailSorokin** [comment]
Review per your comments: 
- The content does indeed change.
- Arrow displays, but is it supposed to do anything yet? What is "Update" and where would that take you, if implemented?

Other comments Review:
- Expenses: Daily - $200. What would that be used for and what is it supposed to represent?
- Text colors + font look good. Match original site.
- How are we supposed to exit this page. If it is the power button, should it take us back to the home page?
- Are you setting up email accounts associated with each user? How will that display?

**Comment by b5er** [comment]
As we discussed these are just placeholders. We'll work on these soon, and solidify this after we get the signup up and running.

Looks like there aren't any bugs, appreciate you reviewing for this.
I will merge this.
